### ISSUE TITLE
project-tree service

### ISSUE THREAD

**Issue by Ginxo** [kiegroup/build-chain-configuration-reader#40]
it is about to move https://github.com/kiegroup/build-chain-configuration-reader/blob/main/src/lib/project-tree.js to typescript
remember not to user typedi and just follow singleton pattern
Move also https://github.com/kiegroup/build-chain-configuration-reader/blob/main/src/lib/helper/definition-interpreter.js methods inside the project-tree as private methods

**Comment by shubhbapna** [comment]
Opening a separate issue for `getOrderedList*` methods due to the confusion about its behavior
