### ISSUE TITLE
add extension mechanism for definition-file

### ISSUE THREAD

**Issue by Ginxo** [kiegroup/build-chain-configuration-reader#57]
- add `extends` keyword to the definition-file schema as it is done for project-dependencies files. Remember it can be filesystem path or URL
- add new allowed version `2.2` at https://github.com/kiegroup/build-chain-configuration-reader/blob/be954cd7afd87c140a2314ae9b4ba6a3296d6fad/src/lib/util/validations.js#L3
- cover new functionality with unitary tests
- behavior will be
  - multiple extensions from parent to parent-parent..., so recursive mechanism should be applied starting from the top one
  - all sections will be merged from the one from parent and the ones from the parent overwritten in case they are duplicated
- add documentation for this new functionality
- increase minor version and this will be published to npmjs registry
- add entry on CHANGELOG
- produce new https://github.com/kiegroup/github-action-build-chain version pointing to the configuration-reader version 
- backport it to typescript/main branch

**Comment by shubhbapna** [comment]
How should merging an `array` be handled? So for eg if we have these dependencies in the parent definition file
```
dependencies: [
        { project: 'kiegroup/lienzo-core', dependencies: [Array] },
        { project: 'kiegroup/lienzo-tests', dependencies: [Array] },
        { project: 'kiegroup/droolsjbpm-build-bootstrap' },
        { project: 'kiegroup/kie-soup', dependencies: [Array] },
        { project: 'kiegroup/appformer', dependencies: [Array] },
        { project: 'kiegroup/droolsjbpm-knowledge', dependencies: [Array] },
        { project: 'kiegroup/drools', dependencies: [Array] },
        { project: 'kiegroup/jbpm', dependencies: [Array] },
]
```
and these in the child
```
dependencies: [
        { project: 'kiegroup/lienzo-tests', dependencies: [some changes] },
        { project: 'kiegroup/new-project', dependencies: [Array] },
]
```
Do we produce the following array?
```
dependencies: [
        { project: 'kiegroup/lienzo-core', dependencies: [some changes + whatever was unchanged] },
        { project: 'kiegroup/lienzo-tests', dependencies: [Array] },
        { project: 'kiegroup/droolsjbpm-build-bootstrap' },
        { project: 'kiegroup/kie-soup', dependencies: [Array] },
        { project: 'kiegroup/appformer', dependencies: [Array] },
        { project: 'kiegroup/droolsjbpm-knowledge', dependencies: [Array] },
        { project: 'kiegroup/drools', dependencies: [Array] },
        { project: 'kiegroup/jbpm', dependencies: [Array] },
        { project: 'kiegroup/new-project', dependencies: [Array] },
]
```

**Comment by Ginxo** [comment]
@shubhbapna the extension mechanism for dependencies is already implemented and we should apply the same, so file-definition information extension mechanism should be about to merge `pre`, `post`, `default` and  `build` sections
