### ISSUE TITLE
`skip` option should add projects while constructing tree

### ISSUE THREAD

**Issue by shubhbapna** [kiegroup/build-chain-configuration-reader#83]
Currently `skip` option does not add the project to the tree. However, we want the project to still be added and cloned but just not executed

**Comment by Ginxo** [comment]
in spite of its name, build-chain is not just for building, is for execution, so let's suppose you want to execute one single command from one single repository for any reason... (we are always talking about maven, but remember build-chain is build system/tool agnostic) so it could be the case where you want to checkout whatever the project set (tree) and you want to execute whatever the command for the whole project set.

Remember we are talking about `commands` section from definition file, another proposal would be to remove it from there and to add `skip` to dependencies section, either at project level and at mapping level (for skipping checkout for specific mapping case), wdyt? @shubhbapna
